[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Hill"]
repository = "https://github.com/alxhill/rust-raytracing"
license = "MIT"

[dependencies]
image = "0.24.5"
num-traits = "0.2.15"
pixel-canvas = "0.2.3"
rand = "0.8.5"

[profile.dev]
opt-level = 3