[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.5"
num-traits = "0.2.15"
pixel-canvas = "0.2.3"
rand = "0.8.5"
bumpalo = "3.12.0"

[profile.dev]
opt-level = 2

[features]
collections = []
boxed = []